#gt1x touchpanel driver

#primary function file
obj-$(CONFIG_TOUCHSCREEN_GT1X)	+= gt1x.o
#implement platform-independent functions
obj-$(CONFIG_TOUCHSCREEN_GT1X)	+= gt1x_generic.o
#support firmware update
obj-$(CONFIG_TOUCHSCREEN_GT1X)	+= gt1x_update.o
#debug tool
obj-$(CONFIG_TOUCHSCREEN_GT1X)	+= gt1x_tools.o
#support HotKnot, Gesture wankeup features.
obj-$(CONFIG_TOUCHSCREEN_GT1X)	+= gt1x_extents.o

